// Top-level BNN testbench — plain Icarus Verilog (no cocotb)
// Reads pixels.mem and weights.mem generated by gen_mem_files.py,
// drives tt_um_mnist_bnn serially, and prints the result.
`timescale 1ns/1ps

module tb_top;

// ---------------------------------------------------------------------------
// DUT signals
// ---------------------------------------------------------------------------
reg        clk;
reg        rst_n;
reg  [7:0] ui_in;   // [0]=mode  [1]=pixel_in  [2]=weight_in
reg  [7:0] uio_in;
wire [7:0] uo_out;  // [3:0]=answer digit
wire [7:0] uio_out;
wire [7:0] uio_oe;

// ---------------------------------------------------------------------------
// DUT
// ---------------------------------------------------------------------------
tt_um_mnist_bnn dut (
    .ui_in  (ui_in),
    .uo_out (uo_out),
    .uio_in (uio_in),
    .uio_out(uio_out),
    .uio_oe (uio_oe),
    .ena    (1'b1),
    .clk    (clk),
    .rst_n  (rst_n)
);

// ---------------------------------------------------------------------------
// Clock: 10 ns period
// ---------------------------------------------------------------------------
initial clk = 0;
always  #5 clk = ~clk;

// ---------------------------------------------------------------------------
// Waveform dump (view with gtkwave)
// ---------------------------------------------------------------------------
initial begin
    $dumpfile("dumpfile.fst");
    $dumpvars(0, tb_top);
end

// ---------------------------------------------------------------------------
// Serial stream memory (one bit per address)
// ---------------------------------------------------------------------------
reg pixel_stream  [0:783];    // 784 pixels
reg weight_stream [0:2319];   // 2320 weight bits (w1+w2+w3)

// ---------------------------------------------------------------------------
// Test configuration
// ---------------------------------------------------------------------------
reg [31:0] num_tests;
reg [31:0] test_indices [0:200];   // 1 count + 100 tests x 2 (index, label) = 201 entries
reg [7:0]  expected_labels [0:99];

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------
integer i, row, col, test_num;
integer passed_tests, failed_tests;
reg [31:0] current_index;
reg [7:0]  current_label;
reg [3:0]  hw_result;
string pixel_filename;

// Pass/fail tracking (store MNIST dataset index for each outcome)
reg [31:0] passed_mnist_idx [0:99];
reg [31:0] failed_mnist_idx [0:99];

// ---------------------------------------------------------------------------
// Main test
// ---------------------------------------------------------------------------
initial begin
    $display("");
    $display("========================================================================");
    $display("=== MNIST BNN Top-Level Hardware Test with Real MNIST Images ===");
    $display("========================================================================");
    $display("TEST START");
    $display("");
    
    // Load test configuration
    $readmemh("test_config.mem", test_indices);
    num_tests = test_indices[0];
    
    // Parse test configuration: extract indices and labels
    for (test_num = 0; test_num < num_tests; test_num = test_num + 1) begin
        expected_labels[test_num] = test_indices[test_num*2 + 2][7:0];
    end
    
    // Load weights (same for all tests)
    $readmemb("weights.mem", weight_stream);
    
    passed_tests = 0;
    failed_tests = 0;
    
    $display("Number of test images: %0d", num_tests);
    $display("");

    // -----------------------------------------------------------------------
    // Loop through all test images
    // -----------------------------------------------------------------------
    for (test_num = 0; test_num < num_tests; test_num = test_num + 1) begin
        current_label = expected_labels[test_num];
        
        $display("========================================================================");
        $display("TEST IMAGE %0d: Expected label = %0d", test_num, current_label);
        $display("========================================================================");
        
        // Load pixel data for this test image
        $sformat(pixel_filename, "MNIST_data_gen/pixels_%0d.mem", test_num);
        $readmemb(pixel_filename, pixel_stream);
        
        // Print input image
        $display("Input image (# = white pixel, . = black pixel):");
        $display("+----------------------------+");
        for (row = 0; row < 28; row = row + 1) begin
            $write("|");
            for (col = 0; col < 28; col = col + 1) begin
                if (pixel_stream[row*28 + col] === 1'b1)
                    $write("#");
                else
                    $write(".");
            end
            $display("|");
        end
        $display("+----------------------------+");
        $display("");

        // Initialise signals
        ui_in  = 8'b0;
        uio_in = 8'b0;
        rst_n  = 1'b0;

        // Reset: hold low for 10 cycles
        repeat(10) @(posedge clk);
        #1 rst_n = 1'b1;
        repeat(2)  @(posedge clk);  // let reset_pipe settle

        // Assert mode=1 → FSM transitions to s_LOAD on next posedge
        $display("[%0t] Entering LOAD state...", $time);
        #1 ui_in = 8'b00000001;   // mode=1, no data yet
        @(posedge clk);

        // Stream 2320 cycles: pixels and weights
        for (i = 0; i < 2320; i = i + 1) begin
            #1 ui_in = {5'b0,
                        weight_stream[i],
                        (i < 784) ? pixel_stream[i] : 1'b0,
                        1'b1};    // bit2=weight, bit1=pixel, bit0=mode
            @(posedge clk);
        end

        $display("[%0t] LOAD complete. Running inference...", $time);
        #1 ui_in = 8'b0;   // drop mode

        // Wait for inference layers (~1770 cycles total)
        repeat(2000) @(posedge clk);

        // Read and check result
        hw_result = uo_out[3:0];
        $display("");
        $display("---------------------------------------------------------------------");
        $display("  Hardware classification: %0d", hw_result);
        $display("  Expected label:          %0d", current_label);
        
        if (hw_result == current_label) begin
            $display("  Result: PASS");
            $display("LOG: %0t : INFO : tb_top : dut.uo_out[3:0] : expected_value: %0d actual_value: %0d", $time, current_label, hw_result);
            passed_mnist_idx[passed_tests] = test_indices[test_num*2 + 1];
            passed_tests = passed_tests + 1;
        end else begin
            $display("  Result: FAIL");
            $display("LOG: %0t : ERROR : tb_top : dut.uo_out[3:0] : expected_value: %0d actual_value: %0d", $time, current_label, hw_result);
            failed_mnist_idx[failed_tests] = test_indices[test_num*2 + 1];
            failed_tests = failed_tests + 1;
        end
        $display("---------------------------------------------------------------------");
        $display("");
        
        // Small delay between tests
        repeat(10) @(posedge clk);
    end

    // -----------------------------------------------------------------------
    // Final summary
    // -----------------------------------------------------------------------
    $display("");
    $display("========================================================================");
    $display("=== FINAL TEST SUMMARY ===");
    $display("========================================================================");
    $display("Total tests:  %0d", num_tests);
    $display("Passed:       %0d", passed_tests);
    $display("Failed:       %0d", failed_tests);
    $display("Success rate: %0d%%", (passed_tests * 100) / num_tests);
    $display("------------------------------------------------------------------------");

    $write("PASSED images (MNIST indices): ");
    for (i = 0; i < passed_tests; i = i + 1) begin
        if (i > 0) $write(", ");
        $write("%0d", passed_mnist_idx[i]);
    end
    $display("");

    $write("FAILED images (MNIST indices): ");
    for (i = 0; i < failed_tests; i = i + 1) begin
        if (i > 0) $write(", ");
        $write("%0d", failed_mnist_idx[i]);
    end
    $display("");

    $display("========================================================================");

    if (failed_tests == 0) begin
        $display("TEST PASSED");
    end else begin
        $display("TEST FAILED");
    end
    $display("");

    $finish;
end

// ---- Timeout watchdog (increased for multiple tests) ---------------
initial begin
    #80000000;   // Increased timeout for multiple images
    $display("ERROR: simulation timeout!");
    $finish;
end

endmodule